const RIVEN_STAT_ALIASES = {
  damage: 'base_damage_/_melee_damage',
  dmg: 'base_damage_/_melee_damage',
  md: 'base_damage_/_melee_damage',
  multi: 'multishot',
  ms: 'multishot',
  as: 'fire_rate_/_attack_speed',
  fr: 'fire_rate_/_attack_speed',
  speed: 'fire_rate_/_attack_speed',
  corpus: 'damage_vs_corpus',
  corp: 'damage_vs_corpus',
  dtc: 'damage_vs_corpus',
  grineer: 'damage_vs_grineer',
  grin: 'damage_vs_grineer',
  dtg: 'damage_vs_grineer',
  infested: 'damage_vs_infested',
  inf: 'damage_vs_infested',
  dti: 'damage_vs_infested',
  impact: 'impact',
  imp: 'impact',
  puncture: 'puncture',
  pun: 'puncture',
  slash: 'slash',
  sl: 'slash',
  cold: 'cold_damage',
  cold_damage: 'cold_damage',
  electric: 'electric_damage',
  elec: 'electric_damage',
  ele: 'electric_damage',
  electricity: 'electric_damage',
  electricity_damage: 'electric_damage',
  electric_damage: 'electric_damage',
  heat: 'heat_damage',
  fire: 'heat_damage',
  heat_damage: 'heat_damage',
  toxin: 'toxin_damage',
  tox: 'toxin_damage',
  toxin_damage: 'toxin_damage',
  combo: 'combo_duration',
  critchance: 'critical_chance',
  cc: 'critical_chance',
  slide: 'slide_attack_critical_chance',
  critdmg: 'critical_damage',
  cd: 'critical_damage',
  finisher: 'finisher_damage',
  fin: 'finisher_damage',
  flight: 'projectile_speed',
  pfs: 'projectile_speed',
  ps: 'projectile_speed',
  ammo: 'ammo_maximum',
  magazine: 'magazine_capacity',
  mag: 'magazine_capacity',
  punch: 'punch_through',
  pt: 'punch_through',
  reload: 'reload_speed',
  rld: 'reload_speed',
  rs: 'reload_speed',
  range: 'range',
  rng: 'range',
  statusc: 'status_chance',
  sc: 'status_chance',
  statusd: 'status_duration',
  sd: 'status_duration',
  recoil: 'recoil',
  rec: 'recoil',
  wr: 'recoil',
  zoom: 'zoom',
  z: 'zoom',
  initc: 'initial_combo',
  initial: 'initial_combo',
  ic: 'initial_combo',
  comboefficiency: 'heavy_attack_efficiency',
  heavy: 'heavy_attack_efficiency',
  eff: 'heavy_attack_efficiency',
  combogainextra: 'combo_chance',
  combogainlost: 'combo_chance',
  combochance: 'combo_chance'
}

const RIVEN_STAT_LABEL = {
  'base_damage_/_melee_damage': 'Damage',
  multishot: 'Multishot',
  'fire_rate_/_attack_speed': 'Fire Rate',
  damage_vs_corpus: 'Dmg Corpus',
  damage_vs_grineer: 'Dmg Grineer',
  damage_vs_infested: 'Dmg Infested',
  impact: 'Impact', puncture: 'Puncture', slash: 'Slash',
  cold: 'Cold', cold_damage: 'Cold',
  electricity: 'Electric', electricity_damage: 'Electric', electric_damage: 'Electric',
  heat: 'Heat', heat_damage: 'Heat',
  toxin: 'Toxin', toxin_damage: 'Toxin',
  combo_duration: 'Combo Duration',
  critical_chance: 'Crit Chance',
  slide_attack_critical_chance: 'Slide Crit',
  critical_damage: 'Crit Damage',
  finisher_damage: 'Finisher',
  projectile_speed: 'Flight Speed',
  ammo_maximum: 'Ammo Max',
  magazine_capacity: 'Magazine',
  punch_through: 'Punch Through',
  reload_speed: 'Reload',
  range: 'Range',
  status_chance: 'Status Chance',
  status_duration: 'Status Duration',
  recoil: 'Recoil',
  zoom: 'Zoom',
  initial_combo: 'Initial Combo',
  heavy_attack_efficiency: 'Heavy Efficiency',
  combo_chance: 'Combo Chance'
}

function resolveRivenStat(token) {
  const t = String(token || '').toLowerCase().trim()
  return RIVEN_STAT_ALIASES[t] || null
}

module.exports = { RIVEN_STAT_ALIASES, RIVEN_STAT_LABEL, resolveRivenStat }
